In [11]:
import sys
sys.path.insert(0, '../Week-5-6-7-8')

import json
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR, NuSVR

from helpers.modeling import identify_column_types, create_preprocessor
from uncertainty import run_conformal, calibration_table, prepare_data_group

with open('../Week-5-6-7-8/results.json', 'r') as f:
    results = json.load(f)

df = pd.read_csv("../Datasets/processed/UHPC_dataset/semantic_recoding_features_50_with_publications.csv")

In [12]:
target_col = 'cs_28d'

# Group-aware split: no publication bleeds across train / val / test
X_train, X_val, X_test, y_train, y_val, y_test = prepare_data_group(
    df, target_col, group_col='paper_reference'
)

pub_train = df.loc[X_train.index, 'paper_reference']
pub_test = df.loc[X_test.index, 'paper_reference']
pub_val  = df.loc[X_val.index,  'paper_reference']

print(f"Train size : {X_train.shape[0]}  ({pub_train.nunique()} publications)")
print(f"Val size   : {X_val.shape[0]}  ({pub_val.nunique()} publications)")
print(f"Test size  : {X_test.shape[0]}  ({pub_test.nunique()} publications)")

numerical_cols, one_hot_columns, k_fold_columns = identify_column_types(X_train)
preprocessor = create_preprocessor(numerical_cols, one_hot_columns, k_fold_columns,
                                   handle_unknown='ignore')
print(f"\nEncoded training shape: {preprocessor.fit_transform(X_train, y_train).shape}")

Train size : 1461  (115 publications)
Val size   : 329  (25 publications)
Test size  : 283  (25 publications)

Encoded training shape: (1461, 69)

In [13]:
pipeline_knn, train_knn, test_knn, q_knn, intervals_knn, calibration_knn = run_conformal(
    KNeighborsRegressor, 'knn', results, 'recoded_50', preprocessor,
    X_train, y_train, X_val, y_val, X_test, y_test, pub_test
)
print(f"Train: {train_knn}")
print(f"Test:  {test_knn}")
print(f"Conformal q (90%): {q_knn:.2f}")
calibration_knn

Train: {'RMSE': np.float64(6.549791070260361), 'MAE': 3.885417120117953, 'R2': 0.9601099924523562, 'Correlation': np.float64(0.9799886467693996), 'Mean_Residual': np.float64(-0.0694675872902154), 'N': 1461}
Test:  {'RMSE': np.float64(22.71878601115441), 'MAE': 17.143023793679394, 'R2': 0.42745663052453675, 'Correlation': np.float64(0.7359099764715195), 'Mean_Residual': np.float64(-6.958370812021887), 'N': 283}
Conformal q (90%): 74.31

,publication,n_rows,mean_true,mean_prediction,coverage,interval_width,mean_residual,mean_distance
0,Ref-107-Research,16,109.031250,111.424252,1.0,148.623231,7.428191,15.121621
1,Ref-11-Research,4,127.750000,115.287702,1.0,148.623231,12.462298,9.939555
2,Ref-113-Research,5,165.055660,170.200181,1.0,148.623231,8.389570,5.889168
3,Ref-114-Research,5,208.804000,191.939738,1.0,148.623231,16.864262,6.097123
4,Ref-116-Research,36,152.627778,154.624389,1.0,148.623231,4.013374,4.158053
5,Ref-117-Research,5,113.000000,113.692291,1.0,148.623231,11.059342,17.842439
6,Ref-121-Research,80,165.075000,182.913925,1.0,148.623231,22.948058,8.820403
7,Ref-126-Research,5,114.600000,142.689382,1.0,148.623231,28.089382,5.621627
8,Ref-127-Research,3,201.200000,153.465759,1.0,148.623231,47.734241,4.881362
9,Ref-128-Research,3,201.266667,200.345212,1.0,148.623231,2.165204,3.440041
10,Ref-147-Research,16,151.625000,147.360652,1.0,148.623231,13.055270,10.685354
11,Ref-150-Research,11,103.545455,108.648585,1.0,148.623231,5.103131,1.240739
12,Ref-160-Research,10,135.700000,155.703780,1.0,148.623231,20.003780,4.559938
13,Ref-17-Research,10,146.400000,136.042512,1.0,148.623231,13.985146,1.762601
14,Ref-26-Research,26,155.534615,160.518348,1.0,148.623231,17.582463,7.771336
15,Ref-35-Research,1,175.000000,167.952978,1.0,148.623231,7.047022,7.313200
16,Ref-40-Research,2,158.500000,130.764231,1.0,148.623231,27.735769,8.439763
17,Ref-44-Research,4,142.750000,111.240159,1.0,148.623231,31.509841,9.721421
18,Ref-53-Research,8,129.000000,149.411440,1.0,148.623231,20.411440,7.241810
19,Ref-68-Research,2,150.500000,167.791910,1.0,148.623231,17.291910,4.737984
20,Ref-69-Research,12,163.000000,180.538049,1.0,148.623231,17.538049,9.259106
21,Ref-71-Research,3,151.366667,175.723178,1.0,148.623231,24.356511,12.075417
22,Ref-81-Research,4,96.135000,125.536849,1.0,148.623231,29.401849,4.703286
23,Ref-89-Research,2,186.500000,134.645290,1.0,148.623231,51.854710,4.780680
24,Ref-93-Research,10,131.300000,133.475912,1.0,148.623231,27.741000,6.768876

In [14]:
pipeline_svr, train_svr, test_svr, q_svr, intervals_svr, calibration_svr = run_conformal(
    SVR, 'svr', results, 'recoded_50', preprocessor,
    X_train, y_train, X_val, y_val, X_test, y_test, pub_test
)
print(f"Train: {train_svr}")
print(f"Test:  {test_svr}")
print(f"Conformal q (90%): {q_svr:.2f}")
calibration_svr

Train: {'RMSE': np.float64(8.40126124316765), 'MAE': 5.4071940633825255, 'R2': 0.9343706347141592, 'Correlation': np.float64(0.9667990257844075), 'Mean_Residual': np.float64(-0.06775276318929017), 'N': 1461}
Test:  {'RMSE': np.float64(26.499205995130957), 'MAE': 20.59534876275175, 'R2': 0.221060244139054, 'Correlation': np.float64(0.635116646889457), 'Mean_Residual': np.float64(-3.9547328885356996), 'N': 283}
Conformal q (90%): 83.52

,publication,n_rows,mean_true,mean_prediction,coverage,interval_width,mean_residual,mean_distance
0,Ref-107-Research,16,109.031250,122.880283,1.0,167.049789,19.392585,6.604180
1,Ref-11-Research,4,127.750000,124.901602,1.0,167.049789,4.751940,3.658512
2,Ref-113-Research,5,165.055660,168.759424,1.0,167.049789,3.703764,3.133568
3,Ref-114-Research,5,208.804000,181.229420,1.0,167.049789,27.574580,2.200367
4,Ref-116-Research,36,152.627778,140.991987,1.0,167.049789,11.635790,1.931499
5,Ref-117-Research,5,113.000000,128.451172,1.0,167.049789,15.451172,8.214006
6,Ref-121-Research,80,165.075000,169.439001,1.0,167.049789,15.123495,3.887524
7,Ref-126-Research,5,114.600000,159.117366,1.0,167.049789,44.517366,2.476770
8,Ref-127-Research,3,201.200000,150.940782,1.0,167.049789,50.259218,2.086621
9,Ref-128-Research,3,201.266667,210.395746,1.0,167.049789,9.129080,2.164416
10,Ref-147-Research,16,151.625000,129.732140,1.0,167.049789,21.892860,3.822633
11,Ref-150-Research,11,103.545455,110.663762,1.0,167.049789,7.118307,1.015664
12,Ref-160-Research,10,135.700000,182.068529,1.0,167.049789,46.368529,1.895212
13,Ref-17-Research,10,146.400000,138.763674,1.0,167.049789,9.877700,1.203187
14,Ref-26-Research,26,155.534615,186.859607,1.0,167.049789,31.324991,2.745213
15,Ref-35-Research,1,175.000000,220.642535,1.0,167.049789,45.642535,3.294791
16,Ref-40-Research,2,158.500000,194.602719,1.0,167.049789,36.102719,3.142654
17,Ref-44-Research,4,142.750000,135.295044,1.0,167.049789,7.454956,3.259266
18,Ref-53-Research,8,129.000000,166.587260,1.0,167.049789,37.587260,2.586086
19,Ref-68-Research,2,150.500000,145.328284,1.0,167.049789,5.171716,2.278378
20,Ref-69-Research,12,163.000000,122.373324,1.0,167.049789,42.148775,4.499813
21,Ref-71-Research,3,151.366667,130.615339,1.0,167.049789,20.751328,4.339410
22,Ref-81-Research,4,96.135000,100.156562,1.0,167.049789,6.877679,2.256376
23,Ref-89-Research,2,186.500000,147.327562,1.0,167.049789,39.172438,2.492705
24,Ref-93-Research,10,131.300000,153.853114,0.9,167.049789,29.792381,3.072411

In [15]:
pipeline_nusvr, train_nusvr, test_nusvr, q_nusvr, intervals_nusvr, calibration_nusvr = run_conformal(
    NuSVR, 'nusvr', results, 'recoded_50', preprocessor,
    X_train, y_train, X_val, y_val, X_test, y_test, pub_test
)
print(f"Train: {train_nusvr}")
print(f"Test:  {test_nusvr}")
print(f"Conformal q (90%): {q_nusvr:.2f}")
calibration_nusvr

Train: {'RMSE': np.float64(8.345009428865133), 'MAE': 5.556364844356813, 'R2': 0.9352465535504952, 'Correlation': np.float64(0.9672652519299139), 'Mean_Residual': np.float64(-0.01251630557359761), 'N': 1461}
Test:  {'RMSE': np.float64(27.34405172102479), 'MAE': 21.205695905824264, 'R2': 0.17060028582318842, 'Correlation': np.float64(0.6113311468749365), 'Mean_Residual': np.float64(-3.043244004587312), 'N': 283}
Conformal q (90%): 86.04

,publication,n_rows,mean_true,mean_prediction,coverage,interval_width,mean_residual,mean_distance
0,Ref-107-Research,16,109.031250,123.098967,1.0,172.081823,19.272839,6.603872
1,Ref-11-Research,4,127.750000,124.549005,1.0,172.081823,6.551198,3.657237
2,Ref-113-Research,5,165.055660,165.723739,1.0,172.081823,1.726145,3.133449
3,Ref-114-Research,5,208.804000,183.378428,1.0,172.081823,26.267590,2.199386
4,Ref-116-Research,36,152.627778,138.754490,1.0,172.081823,13.873288,1.931494
5,Ref-117-Research,5,113.000000,126.857361,1.0,172.081823,13.857361,8.213561
6,Ref-121-Research,80,165.075000,168.755458,1.0,172.081823,15.317576,3.886623
7,Ref-126-Research,5,114.600000,170.166651,1.0,172.081823,55.566651,2.476634
8,Ref-127-Research,3,201.200000,151.581441,1.0,172.081823,49.618559,2.086791
9,Ref-128-Research,3,201.266667,209.518416,1.0,172.081823,8.251749,2.164416
10,Ref-147-Research,16,151.625000,126.324713,1.0,172.081823,25.300287,3.822290
11,Ref-150-Research,11,103.545455,110.850872,1.0,172.081823,7.305417,1.015664
12,Ref-160-Research,10,135.700000,183.080518,1.0,172.081823,47.380518,1.894273
13,Ref-17-Research,10,146.400000,137.438092,1.0,172.081823,11.054116,1.203175
14,Ref-26-Research,26,155.534615,185.782459,1.0,172.081823,30.247844,2.744478
15,Ref-35-Research,1,175.000000,210.750614,1.0,172.081823,35.750614,3.294699
16,Ref-40-Research,2,158.500000,193.094737,1.0,172.081823,34.594737,3.141931
17,Ref-44-Research,4,142.750000,135.717880,1.0,172.081823,7.032120,3.258170
18,Ref-53-Research,8,129.000000,166.244918,1.0,172.081823,37.244918,2.585427
19,Ref-68-Research,2,150.500000,143.940758,1.0,172.081823,6.559242,2.278372
20,Ref-69-Research,12,163.000000,117.190917,1.0,172.081823,47.249864,4.504396
21,Ref-71-Research,3,151.366667,136.676525,1.0,172.081823,14.690141,4.338782
22,Ref-81-Research,4,96.135000,101.758225,1.0,172.081823,7.386535,2.256553
23,Ref-89-Research,2,186.500000,145.861729,1.0,172.081823,40.638271,2.491995
24,Ref-93-Research,10,131.300000,151.245368,1.0,172.081823,25.910529,3.078412

In [18]:
poor_coverage_threshold = 1

poor_coverage = pd.concat([
    calibration_knn.assign(model='knn'),
    calibration_svr.assign(model='svr'),
    calibration_nusvr.assign(model='nusvr'),
])
poor_coverage = (
    poor_coverage[poor_coverage['coverage'] < poor_coverage_threshold]
    .sort_values('coverage')
    [['model', 'publication', 'n_rows', 'coverage', 'interval_width', 'mean_residual', 'mean_distance']]
    .reset_index(drop=True)
)

print(f"Publications below {poor_coverage_threshold:.0%} coverage: {poor_coverage['publication'].nunique()} unique, {len(poor_coverage)} model-publication pairs")
poor_coverage

Publications below 100% coverage: 1 unique, 1 model-publication pairs

,model,publication,n_rows,coverage,interval_width,mean_residual,mean_distance
0,svr,Ref-93-Research,10,0.9,167.049789,29.792381,3.072411

In [ ]:
import matplotlib.pyplot as plt

all_cal = pd.concat([
    calibration_knn.assign(model='knn'),
    calibration_svr.assign(model='svr'),
    calibration_nusvr.assign(model='nusvr'),
], ignore_index=True)

colors = {'knn': 'steelblue', 'svr': 'tomato', 'nusvr': 'seagreen'}

fig, ax = plt.subplots(figsize=(9, 6))

for model_name, grp in all_cal.groupby('model'):
    ax.scatter(grp['mean_distance'], grp['mean_residual'],
               label=model_name.upper(), color=colors[model_name],
               alpha=0.7, edgecolors='white', linewidths=0.4, s=60)

# label outliers: top 5 by mean_residual per model
for model_name, grp in all_cal.groupby('model'):
    for _, row in grp.nlargest(5, 'mean_residual').iterrows():
        ax.annotate(row['publication'].replace('-Research', '').replace('-data', ''),
                    xy=(row['mean_distance'], row['mean_residual']),
                    fontsize=7, color=colors[model_name],
                    xytext=(4, 2), textcoords='offset points')

ax.set_xlabel('Mean Distance to Training (5-NN)', fontsize=11)
ax.set_ylabel('Mean Absolute Residual (MPa)', fontsize=11)
ax.set_title('Distance vs Residual per Publication — Group Split', fontsize=12)
ax.legend()
ax.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

In [20]:
print(q_knn, q_svr, q_nusvr)

74.31161544924942 83.52489458133604 86.04091140249217