# Week 5: UHPC Dataset Preprocessing and Analysis

## Objective

This notebook explores preprocessing and cleaning techniques for the UHPC concrete dataset.

Main goals:
- Understand messy real-world datasets
- Handle missing and text values
- Apply preprocessing techniques
- Encode different data types
- Prepare machine learning ready data

In [ ]:
# Week 5 - UHPC Dataset Preprocessing
# Step 1: Import Libraries


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries Imported Successfully")

Libraries Imported Successfully

# Step 2 Check Available Files

In this step, we check all files available
inside the current working directory.

This helps avoid file path errors.

In [61]:
import os

print(os.listdir())

['Summary of Dataset (Version-2).xlsx', 'cleaned_cement_dataset.csv', 'Description (Version-2).docx', 'Readme  (Version-2).txt', 'week5_uhpc_preprocessing.ipynb', 'UHPC Dataset  (Version-2).xlsx']

# Step 3 Load UHPC Dataset

In this step, we load the UHPC dataset
using pandas and preview the dataset.

In [62]:
import pandas as pd

df = pd.read_excel("UHPC Dataset  (Version-2).xlsx")

print(df.head())

   Unnamed: 0  Unnamed: 1  Unnamed: 2  \
0         NaN         NaN         NaN
1         NaN         NaN         NaN
2         NaN         NaN         NaN
3         NaN         NaN         NaN
4         NaN         NaN         NaN

                                          Unnamed: 3
0  Readme \n\nThe Excel file is organized into mu...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

# Inspect UHPC Dataset

In this step, we inspect:
- dataset size
- column names
- data types
- missing values

This helps us understand the dataset before cleaning and preprocessing.

In [63]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Information:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape:
(30, 4)

Column Names:
Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3'], dtype='str')

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  0 non-null      float64
 2   Unnamed: 2  0 non-null      float64
 3   Unnamed: 3  2 non-null      str
dtypes: float64(3), str(1)
memory usage: 1.1 KB
None

Missing Values:
Unnamed: 0    30
Unnamed: 1    30
Unnamed: 2    30
Unnamed: 3    28
dtype: int64

# Step 5 Inspect Raw Excel File

In this step, we inspect the raw Excel structure
to understand why the dataset was imported incorrectly.

This helps identify:
- useless top rows
- actual header row
- merged cells
- dataset starting position

In [64]:
raw_df = pd.read_excel(
    "UHPC Dataset  (Version-2).xlsx",
    header=None
)

print(raw_df.head(15))

     0   1   2                                                  3
0  NaN NaN NaN                                                NaN
1  NaN NaN NaN  Readme \n\nThe Excel file is organized into mu...
2  NaN NaN NaN                                                NaN
3  NaN NaN NaN                                                NaN
4  NaN NaN NaN                                                NaN
5  NaN NaN NaN                                                NaN
6  NaN NaN NaN                                                NaN
7  NaN NaN NaN                                                NaN
8  NaN NaN NaN                                                NaN
9  NaN NaN NaN                                                NaN
10 NaN NaN NaN                                                NaN
11 NaN NaN NaN                                                NaN
12 NaN NaN NaN                                                NaN
13 NaN NaN NaN                                                NaN
14 NaN NaN NaN                                                NaN

# Step 6 Find Actual Dataset Starting Row

In this step, we inspect more rows from the raw Excel file
to identify:
- actual column headers
- dataset starting row
- unnecessary rows to skip

In [66]:
print(raw_df.head(40))

     0   1   2                                                  3
0  NaN NaN NaN                                                NaN
1  NaN NaN NaN  Readme \n\nThe Excel file is organized into mu...
2  NaN NaN NaN                                                NaN
3  NaN NaN NaN                                                NaN
4  NaN NaN NaN                                                NaN
5  NaN NaN NaN                                                NaN
6  NaN NaN NaN                                                NaN
7  NaN NaN NaN                                                NaN
8  NaN NaN NaN                                                NaN
9  NaN NaN NaN                                                NaN
10 NaN NaN NaN                                                NaN
11 NaN NaN NaN                                                NaN
12 NaN NaN NaN                                                NaN
13 NaN NaN NaN                                                NaN
14 NaN NaN NaN                                                NaN
15 NaN NaN NaN                                                NaN
16 NaN NaN NaN                                                NaN
17 NaN NaN NaN                                                NaN
18 NaN NaN NaN                                                NaN
19 NaN NaN NaN                                                NaN
20 NaN NaN NaN                                                NaN
21 NaN NaN NaN                                                NaN
22 NaN NaN NaN                                                NaN
23 NaN NaN NaN                                                NaN
24 NaN NaN NaN                                                NaN
25 NaN NaN NaN                                                NaN
26 NaN NaN NaN                                                NaN
27 NaN NaN NaN                                                NaN
28 NaN NaN NaN                                                NaN
29 NaN NaN NaN                                                NaN
30 NaN NaN NaN  Nomenclatures\nSCMs =  Supplementary Cementiti...

# Step 7 Check Excel Sheet Names

In this step, we inspect all sheet names
inside the Excel file.

This helps identify:
- documentation sheets
- actual dataset sheets
- metadata sheets

In [67]:
excel_file = pd.ExcelFile("UHPC Dataset  (Version-2).xlsx")

print(excel_file.sheet_names)

['Readme', 'UHPC Dataset ', 'Reference and Data sources', 'Testing Standard ', 'Cement Composition', 'Silica Fume Composition ', 'Slag Composition ', 'Flyash Composition ', 'Limestone Composition ', 'Metakaolin Composition  ', 'Glass Powder Composition ', 'Rice Hush Ash Composition ', 'Crushed Quartz Composition  ', 'Nano Particle Composition  ', 'Fillers Composition ']

# Step 8 Load Correct UHPC Dataset Sheet

In this step, we load the actual UHPC dataset
from the correct Excel sheet.

The previous sheet contained only documentation.

In [68]:
df = pd.read_excel(
    "UHPC Dataset  (Version-2).xlsx",
    sheet_name="UHPC Dataset "
)

print(df.head())

          Mix-ID      Mix Constitutents   \
0            NaN                 Binder
1            NaN  Cement Amount  (kg/m³)
2        S10-F10                     839
3      S10-F5-N5                     839
4  S10-F2.5-N7.5                     839

                             Unnamed: 2          Unnamed: 3  \
0                                   NaN                 NaN
1                         Cement type\t  Cement Grade (Mpa)
2  Type I/II low-alkali portland cement                 NaN
3  Type I/II low-alkali portland cement                 NaN
4  Type I/II low-alkali portland cement                 NaN

                                    Unnamed: 4                Unnamed: 5  \
0  Supplementary Cementitious Materials (SCMs)                       NaN
1                          Silica Fume (kg/m³)  Flayash Amount   (kg/m³)
2                                          104                       104
3                                          104                        52
4                                          104                        26

      Unnamed: 6                 Unnamed: 7            Unnamed: 8  \
0            NaN                        NaN                   NaN
1  Fly Ash Type   Limestone Powder  (kg/m3)  Quartzpowder (kg/m3)
2        Class-F                          0                     0
3        Class-F                          0                     0
4        Class-F                          0                     0

             Unnamed: 9  ...           Unnamed: 82 Unnamed: 83  \
0                   NaN  ...  Freezing and Thawing         NaN
1  Glass powder (kg/m3)  ...    Testing Standards      Cycles
2                     0  ...             ASTM C666         105
3                     0  ...             ASTM C666         106
4                     0  ...             ASTM C666         106

                        Unnamed: 84                     Unnamed: 85  \
0  Rapid Chloride Permeability Test                             NaN
1                Testing Standards   Total Charge Passed (Coulombs)
2                        ASTM C1202                             165
3                        ASTM C1202                             142
4                        ASTM C1202                             136

           Unnamed: 86                  Unnamed: 87 Research Paper Details  \
0  Surface Resistivity                          NaN     Country of Origin
1   Testing Standards   Surface Resistivity (kΩ-mm)                    NaN
2         AASHTO T 358                          386                    USA
3         AASHTO T 358                          424                    NaN
4         AASHTO T 358                          463                    NaN

                                         Unnamed: 89       Unnamed: 90  \
0                   Reference details/Data sources\n  Year of Publish
1                                                NaN               NaN
2  Alternative Supplementary Cementitious Materia...              2022
3                                                NaN               NaN
4                                                NaN               NaN

                             Unnamed: 91
0  Research paper reference in dataset\n
1                                    NaN
2                             Ref-1-data
3                                    NaN
4                                    NaN

[5 rows x 92 columns]

# Step 9 Inspect Dataset Dimensions

In this step, we inspect:
- total number of rows
- total number of columns

This helps understand the overall dataset size.

In [70]:
print(df.shape)

(2190, 92)

# Step 10 Inspect Dataset Columns

In this step, we inspect all dataset columns
to identify:
- feature names
- unnamed columns
- metadata columns
- preprocessing requirements

This helps understand the dataset structure
before cleaning the dataframe.

In [71]:
print(df.columns.tolist())

['Mix-ID', 'Mix Constitutents ', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Curing Regime ', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Workability ', 'Unnamed: 44', 'Unnamed: 45', 'Mechanical Properties ', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Durability Properities ', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Research Paper Details', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91']

# Step 11  Identify Unnamed Columns

In this step, we identify unnamed columns
generated because of merged Excel formatting.

This helps understand:
- messy headers
- formatting issues
- preprocessing requirements

In [72]:
unnamed_columns = [
    col for col in df.columns
    if "Unnamed" in str(col)
]

print(unnamed_columns)

['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91']

# Step 12 Check Missing Values

In this step, we inspect missing values
in the dataset.

This helps identify:
- empty columns
- incomplete features
- preprocessing requirements

In [73]:
print(df.isnull().sum())

Mix-ID                     216
Mix Constitutents            0
Unnamed: 2                  63
Unnamed: 3                 861
Unnamed: 4                   0
                          ...
Unnamed: 87               2176
Research Paper Details    2021
Unnamed: 89               2021
Unnamed: 90               2024
Unnamed: 91               2021
Length: 92, dtype: int64

# Step 13 Remove Highly Missing Columns

In this step, we remove columns
containing too many missing values.

This helps:
- improve dataset quality
- simplify preprocessing
- prepare data for machine learning

In [74]:
df_cleaned = df.dropna(
    axis=1,
    thresh=500
)

print(df_cleaned.shape)

(2190, 41)

# Step 14 Inspect Remaining Columns

In this step, we inspect the columns
remaining after dataset cleaning.

This helps:
- understand cleaned dataset structure
- identify useful features
- prepare for machine learning

In [75]:
print(df_cleaned.columns.tolist())

['Mix-ID', 'Mix Constitutents ', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Curing Regime ', 'Unnamed: 40', 'Unnamed: 41', 'Workability ', 'Unnamed: 45', 'Mechanical Properties ', 'Unnamed: 47', 'Unnamed: 50', 'Unnamed: 53', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 69']

# Step 15  Display Cleaned Dataset

In this step, we display the cleaned dataset
to inspect the remaining features and values.

This helps:
- verify preprocessing
- inspect useful columns
- understand dataset structure

In [76]:
df_cleaned.head()

,Mix-ID,Mix Constitutents,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 41,Workability,Unnamed: 45,Mechanical Properties,Unnamed: 47,Unnamed: 50,Unnamed: 53,Unnamed: 65,Unnamed: 66,Unnamed: 69
0,NaN,Binder,NaN,NaN,Supplementary Cementitious Materials (SCMs),NaN,NaN,NaN,NaN,NaN,...,Humidity (%),Testing Standard,Slump Flow (mm),Compressive Strength (Mpa),NaN,NaN,NaN,Flexural Strength Parameters,NaN,NaN
1,NaN,Cement Amount (kg/m³),Cement type\t,Cement Grade (Mpa),Silica Fume (kg/m³),Flayash Amount (kg/m³),Limestone Powder (kg/m3),Quartzpowder (kg/m3),Glass powder (kg/m3),Rice husk ash (kg/m3),...,NaN,NaN,NaN,Specimen,Testing Standard,7-Day,28-Day,Specimens,Testing Standard,Peak Strength (MPa)
2,S10-F10,839,Type I/II low-alkali portland cement,NaN,104,104,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,380,100 x 100 x 100,BS1881,115,135,76×102×406,ASTM C1609,19.55
3,S10-F5-N5,839,Type I/II low-alkali portland cement,NaN,104,52,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,104.5,132,76×102×406,ASTM C1609,21.25
4,S10-F2.5-N7.5,839,Type I/II low-alkali portland cement,NaN,104,26,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,102.5,122.5,76×102×406,ASTM C1609,20.8

# Step 16 Fix Dataset Headers

In this step, we assign proper feature names
to the dataframe columns.

This helps:
- remove unnamed headers
- improve dataset readability
- prepare structured data for machine learning

In [77]:
df_cleaned.columns = df_cleaned.iloc[1]

df_cleaned = df_cleaned[2:]

df_cleaned.head()

1,NaN,Cement Amount (kg/m³),Cement type\t,Cement Grade (Mpa),Silica Fume (kg/m³),Flayash Amount (kg/m³),Limestone Powder (kg/m3),Quartzpowder (kg/m3),Glass powder (kg/m3),Rice husk ash (kg/m3),...,NaN,NaN,NaN,Specimen,Testing Standard,7-Day,28-Day,Specimens,Testing Standard,Peak Strength (MPa)
2,S10-F10,839,Type I/II low-alkali portland cement,NaN,104,104,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,380,100 x 100 x 100,BS1881,115,135,76×102×406,ASTM C1609,19.55
3,S10-F5-N5,839,Type I/II low-alkali portland cement,NaN,104,52,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,104.5,132,76×102×406,ASTM C1609,21.25
4,S10-F2.5-N7.5,839,Type I/II low-alkali portland cement,NaN,104,26,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,102.5,122.5,76×102×406,ASTM C1609,20.8
5,S10-N10,839,Type I/II low-alkali portland cement,NaN,104,0,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,100.5,116,76×102×406,ASTM C1609,20
6,S10-F5-M5,839,Type I/II low-alkali portland cement,NaN,104,52,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,380,100 x 100 x 100,BS1881,108.5,134,76×102×406,ASTM C1609,20.9

# Step 17  Reset Dataset Index

In this step, we reset dataframe indexing.

This helps:
- create clean row numbering
- improve dataframe readability
- maintain structured preprocessing

In [78]:
df_cleaned = df_cleaned.reset_index(drop=True)

df_cleaned.head()

1,NaN,Cement Amount (kg/m³),Cement type\t,Cement Grade (Mpa),Silica Fume (kg/m³),Flayash Amount (kg/m³),Limestone Powder (kg/m3),Quartzpowder (kg/m3),Glass powder (kg/m3),Rice husk ash (kg/m3),...,NaN,NaN,NaN,Specimen,Testing Standard,7-Day,28-Day,Specimens,Testing Standard,Peak Strength (MPa)
0,S10-F10,839,Type I/II low-alkali portland cement,NaN,104,104,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,380,100 x 100 x 100,BS1881,115,135,76×102×406,ASTM C1609,19.55
1,S10-F5-N5,839,Type I/II low-alkali portland cement,NaN,104,52,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,104.5,132,76×102×406,ASTM C1609,21.25
2,S10-F2.5-N7.5,839,Type I/II low-alkali portland cement,NaN,104,26,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,102.5,122.5,76×102×406,ASTM C1609,20.8
3,S10-N10,839,Type I/II low-alkali portland cement,NaN,104,0,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,100.5,116,76×102×406,ASTM C1609,20
4,S10-F5-M5,839,Type I/II low-alkali portland cement,NaN,104,52,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,380,100 x 100 x 100,BS1881,108.5,134,76×102×406,ASTM C1609,20.9

# Step 18  Remove Remaining Extra Header Row

In this step, we remove the remaining unnecessary header row.

This helps:
- clean dataframe structure
- keep only actual data rows
- improve preprocessing quality

In [79]:
df_cleaned = df_cleaned[1:]

df_cleaned = df_cleaned.reset_index(drop=True)

df_cleaned.head()

1,NaN,Cement Amount (kg/m³),Cement type\t,Cement Grade (Mpa),Silica Fume (kg/m³),Flayash Amount (kg/m³),Limestone Powder (kg/m3),Quartzpowder (kg/m3),Glass powder (kg/m3),Rice husk ash (kg/m3),...,NaN,NaN,NaN,Specimen,Testing Standard,7-Day,28-Day,Specimens,Testing Standard,Peak Strength (MPa)
0,S10-F5-N5,839,Type I/II low-alkali portland cement,NaN,104,52,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,104.5,132,76×102×406,ASTM C1609,21.25
1,S10-F2.5-N7.5,839,Type I/II low-alkali portland cement,NaN,104,26,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,102.5,122.5,76×102×406,ASTM C1609,20.8
2,S10-N10,839,Type I/II low-alkali portland cement,NaN,104,0,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,100.5,116,76×102×406,ASTM C1609,20
3,S10-F5-M5,839,Type I/II low-alkali portland cement,NaN,104,52,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,380,100 x 100 x 100,BS1881,108.5,134,76×102×406,ASTM C1609,20.9
4,S10-F2.5-M7.5,839,Type I/II low-alkali portland cement,NaN,104,26,0,0,0,0,...,NaN,ASTM C143 for Slump\nASTM C1611 for Slump Flow,370,100 x 100 x 100,BS1881,108.5,131.5,76×102×406,ASTM C1609,20.5

# Step 19  Check Final Dataset Shape

In [80]:
print(df_cleaned.shape)

(2187, 41)

# Step 20 Save Cleaned Dataset

In [82]:
df_cleaned.to_excel(
    "UHPC_Cleaned_Dataset.xlsx",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!